# Section 6.1: Sample Verification Unit Tests

import json
import wave
from pathlib import Path
from PIL import Image
import pandas as pd
import pytest

SAMPLE_DIR = Path("data/samples")
GT_DIR = SAMPLE_DIR / "ground_truth"

def test_generated_samples_exist():
    """Verifies that all expected modality files were generated by scripts/generate_samples.py."""
    expected_files = [
        SAMPLE_DIR / "home_health_policy.pdf",
        SAMPLE_DIR / "patient_care_protocol.pdf",
        SAMPLE_DIR / "insurance_card_front.png",
        SAMPLE_DIR / "insurance_card_back.png",
        SAMPLE_DIR / "medication_chart.png",
        SAMPLE_DIR / "visit_schedule_board.png",
        SAMPLE_DIR / "home_health_visits.csv",
        SAMPLE_DIR / "medical_supplies_inventory.csv",
        SAMPLE_DIR / "nurse_visit_note_001.wav",
        SAMPLE_DIR / "care_coordination_call.wav",
        SAMPLE_DIR / "shift_handoff_summary.wav",
        GT_DIR / "expected_truth.json"
    ]
    for file_path in expected_files:
        assert file_path.exists(), f"Expected file does not exist: {file_path}"
        assert file_path.stat().st_size > 0, f"Expected file is empty: {file_path}"

def test_generated_images_loadable():
    """Verifies that all generated PNG images are valid and loadable by PIL."""
    image_files = [
        SAMPLE_DIR / "insurance_card_front.png",
        SAMPLE_DIR / "insurance_card_back.png",
        SAMPLE_DIR / "medication_chart.png",
        SAMPLE_DIR / "visit_schedule_board.png",
    ]
    for img_path in image_files:
        with Image.open(img_path) as img:
            assert img.format == "PNG"
            assert img.width == 640
            assert img.height == 400

def test_generated_tables_parseable():
    """Verifies that the generated CSV files are valid and can be parsed by pandas."""
    csv_visits = SAMPLE_DIR / "home_health_visits.csv"
    csv_supplies = SAMPLE_DIR / "medical_supplies_inventory.csv"

    df_v = pd.read_csv(csv_visits)
    assert len(df_v) == 500
    assert "patient_id" in df_v.columns
    assert "billing_amount" in df_v.columns

    df_s = pd.read_csv(csv_supplies)
    assert len(df_s) == 200
    assert "supply_id" in df_s.columns
    assert "unit_price" in df_s.columns

def test_generated_audios_have_duration():
    """Verifies that the generated WAV files are valid audio files with nonzero duration."""
    audio_files = [
        SAMPLE_DIR / "nurse_visit_note_001.wav",
        SAMPLE_DIR / "care_coordination_call.wav",
        SAMPLE_DIR / "shift_handoff_summary.wav"
    ]
    for wav_path in audio_files:
        with wave.open(str(wav_path), 'rb') as w:
            assert w.getnchannels() == 1
            assert w.getsampwidth() == 2 # 16-bit
            assert w.getframerate() == 16000
            num_frames = w.getnframes()
            assert num_frames > 0
            duration = num_frames / 16000
            assert duration > 0.0

def test_ground_truth_metadata():
    """Verifies that the ground truth JSON contains entries for all generated assets."""
    gt_path = GT_DIR / "expected_truth.json"
    with open(gt_path, "r") as f:
        data = json.load(f)
    
    assert "nurse_visit_note_001.wav" in data
    assert "insurance_card_front.png" in data
    assert "home_health_visits.csv" in data
    
    entry = data["nurse_visit_note_001.wav"]
    assert entry["modality"] == "audio"
    assert len(entry["transcript_contains"]) > 0
